# Velodyne LiDAR Network Configuration
# Copy to /etc/netplan/99-velodyne.yaml and run: sudo netplan apply

network:
  version: 2
  renderer: networkd
  ethernets:
    # Velodyne LiDAR Interface
    enp2s0:  # Replace with actual interface name
      addresses:
        - 192.168.1.100/24
      dhcp4: false
      dhcp6: false
      optional: true
      # Set MTU for high-speed data transfer
      mtu: 9000
      
    # Main network interface (example)
    enp1s0:
      dhcp4: true
      dhcp6: false
      optional: true
      
  # Static routes for LiDAR communication
  routes:
    - to: 192.168.1.0/24
      via: 192.168.1.1
      metric: 100